import { course } from '@/lib/drizzle/schema/public';

export const courseList: typeof course.$inferInsert[] = [
    {
        name: 'マクロ経済学',
        targetGrade: '1学年',
        targetFaculty: '経済学部',
        targetDepartment: '経済学科',
        week: '月曜日',
        period: '1限目',
        credit: '2',
        required: '必修',
        classroom: 'L110',
        professor: '佐藤',
    },
    {
        name: 'ミクロ経済学',
        targetGrade: '1学年',
        targetFaculty: '経済学部',
        targetDepartment: '経済学科',
        week: '金曜日',
        period: '1限目',
        credit: '2',
        required: '必修',
        classroom: 'L113',
        professor: '高橋',
    },
    {
        name: '統計学',
        targetGrade: '1学年',
        targetFaculty: '経済学部',
        targetDepartment: '経済学科',
        week: '水曜日',
        period: '1限目',
        credit: '2',
        required: '選択必修',
        classroom: 'L115',
        professor: '上田',
    },
    {
        name: '計量経済学',
        targetGrade: '1学年',
        targetFaculty: '経済学部',
        targetDepartment: '経済学科',
        week: '火曜日',
        period: '2限目',
        credit: '2',
        required: '任意',
        classroom: 'L113',
        professor: '上田',
    },
    {
        name: '経営学総論',
        targetGrade: '1学年',
        targetFaculty: '経済学部',
        targetDepartment: '経営学科',
        week: '金曜日',
        period: '1限目',
        credit: '2',
        required: '選択必修',
        classroom: 'L112',
        professor: '宮本',
    },
    {
        name: '産業組織論',
        targetGrade: '2学年',
        targetFaculty: '経済学部',
        targetDepartment: '経済学科',
        week: '木曜日',
        period: '3限目',
        credit: '2',
        required: '任意',
        classroom: 'L117',
        professor: '田中',
    },
    {
        name: '簿記論',
        targetGrade: '1学年',
        targetFaculty: '経済学部',
        targetDepartment: '経営学科',
        week: '木曜日',
        period: '1限目',
        credit: '2',
        required: '任意',
        classroom: 'L211',
        professor: '川崎',
    },
    {
        name: '政治経済学',
        targetGrade: '2学年',
        targetFaculty: '経済学部',
        targetDepartment: '経済学科',
        week: '金曜日',
        period: '4限目',
        credit: '2',
        required: '選択必修',
        classroom: 'L213',
        professor: '上田',
    },
    {
        name: '民法',
        targetGrade: '2学年',
        week: '木曜日',
        period: '2限目',
        credit: '2',
        required: '任意',
        classroom: 'L216',
        professor: '三輪'
    },
    {
        name: '英語ⅰ',
        targetGrade: '1学年',
        week: '金曜日',
        period: '4限目',
        credit: '1',
        required: '必修',
        classroom: 'L113',
        professor: '長岡'
    },
    {
        name: 'ドイツ語',
        targetGrade: '1学年',
        week: '火曜日',
        period: '2限目',
        credit: '1',
        required: '必修',
        classroom: 'L114',
        professor: '新井'
    },
    {
        name: 'フランス語',
        targetGrade: '1学年',
        week: '水曜日',
        period: '3限目',
        credit: '1',
        required: '必修',
        classroom: 'L114',
        professor: '石川'
    },
    {
        name: 'イスラーム史',
        targetGrade: '1学年',
        week: '月曜日',
        period: '4限目',
        credit: '2',
        required: '任意',
        classroom: 'L107',
        professor: '長谷川'
    },
    {
        name: '西洋史',
        targetGrade: '1学年',
        week: '水曜日',
        period: '3限目',
        credit: '2',
        required: '任意',
        classroom: 'L107',
        professor: '橋本'
    },
    {
        name: '日本史',
        targetGrade: '1学年',
        week: '木曜日',
        period: '5限目',
        credit: '2',
        required: '任意',
        classroom: 'L106',
        professor: '松永'
    },
    {
        name: '経済学史',
        targetGrade: '2学年',
        targetFaculty: '経済学部',
        week: '月曜日',
        period: '4限目',
        credit: '2',
        required: '任意',
        classroom: 'L106',
        professor: '飯田'
    },
    {
        name: '会計学ⅰ',
        targetGrade: '2学年',
        targetFaculty: '経済学部',
        targetDepartment: '経営学科',
        week: '火曜日',
        period: '5限目',
        credit: '2',
        required: '任意',
        classroom: 'L206',
        professor: '加藤'
    },
    {
        name: '生態学ⅰ',
        targetGrade: '2学年',
        targetFaculty: '理学部',
        targetDepartment: '生物学科',
        week: '木曜日',
        period: '2限目',
        credit: '2',
        required: '選択必修',
        classroom: 'L103',
        professor: '吉田'
    },
    {
        name: '食品科学',
        targetGrade: '2学年',
        targetFaculty: '農学部',
        targetDepartment: '生物資源学科',
        week: '金曜日',
        period: '4限目',
        credit: '2',
        required: '任意',
        classroom: 'L207',
        professor: '中川'
    }
]



